### ISSUE TITLE
NoMethodError while starting app with gem v1.4.0

### ISSUE THREAD

**Issue by ledermann** [inertiajs/inertia-rails#39]
Using `inertia_rails` v1.4.0 can abort application start with this error message (caused by #38):

```
NoMethodError: undefined method `thread_mattr_accessor' for InertiaRails:Module
```

Example here:
https://github.com/ledermann/pingcrm/pull/235/checks?check_run_id=856003834

Not every Rails application is affected. If an application uses `require "rails/all"` (see [The Rails Initialization Process](https://guides.rubyonrails.org/initialization.html#loading-rails)), all works fine, because `ActionText` requires this module [explicitly](https://github.com/rails/rails/blob/v6.0.3.2/actiontext/lib/action_text/content.rb#L3). But if the frameworks are picked selectively (leaving out `ActionText`), the module may be missing and the startup may fail.

There is a workaround by adding this line to `application.rb` of the application:

```ruby
require "active_support/core_ext/module/attribute_accessors_per_thread"
```

As a fix, this `require` statement should be added to the gem.

**Comment by bknoles** [comment]
wow, great find @ledermann... you really do a great job of keeping us honest against multiple versions of Rails.

i guess it would be _better_ to continue supporting Rails 4 if we can... `thread_mattr_accessor` is just syntactic sugar around `Thread.current`... it shouldn't be super difficult for me to rewrite this to remove the reliance on it.

what are your opinions? is keeping Rails 4 support a good idea?

**Comment by BrandonShar** [comment]
It looks like last year's release of Rails 6 officially marked end of support for Rails 4 by the Rails team. It would be great if we could find usage statistics somewhere, though.

Absent finding out that a significant amount of rails apps are still on 4, I think I would vote in favor of abandoning rails 4 support. This is a minor issue, but I would imagine these will continue to creep up.

**Comment by ledermann** [comment]
Rails 4 has reached EOL, but some weeks ago there was still a security update ([4.2.11.3](https://github.com/rails/rails/releases/tag/v4.2.11.3))

Inertia is very young. I don't think there is a significant amount of Rails 4 apps out there using Inertia. So, for me it's ok to drop support for Rails 4.
